# Generated by Django 6.0.7 on 2026-09-13 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان العرض / البنر')),
                ('subtitle', models.CharField(blank=True, max_length=250, verbose_name='وصف قصير')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='صورة البنر')),
                ('link', models.CharField(blank=True, max_length=300, verbose_name='رابط التوجيه (اختياري)')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'بنر إعلاني',
                'verbose_name_plural': 'البنرات الإعلانية',
            },
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['order'], 'verbose_name': 'صورة للمعرض', 'verbose_name_plural': 'صور معرض المنتج'},
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('in_stock', 'تسليم فوري (متاح)'), ('on_demand', 'متاح بالطلب / تصنيع'), ('out_of_stock', 'غير متاح حالياً')], default='in_stock', max_length=20, verbose_name='حالة التوفر'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='ترتيب العرض'),
        ),
    ]
